### ISSUE TITLE
Only issue is that SHUBHANKAR GUPTA IS 1000% more pro than what he has mentioned on his site 

### ISSUE THREAD

**Issue by hashsaksham** [shubhaankargupta/blueddddd#1]
Forever a bhakt of shubhankar
JAI SHUBHANKAR

**Comment by shubhaankargupta** [comment]
arre sir sab tujhse seekha he

**Comment by hashsaksham** [comment]
Kahan SIR... AAP TOH BHAGVAAN KE ROOP MEIN PRAKAT HOYE HO DHARTI PE.... 

REASONS SHUBHANKAR IS GOD:
1. If you need reasons, you should die and SHUBHANKAR himself will banish you from stepping on earth 

**_Forever a bhakt of shubhankar
JAI SHUBHANKAR_**

**Comment by Samik-Tuteja** [comment]
**_JAI SHUBHANKAR 🙏_**

**Comment by GarvJain03** [comment]
**HAMARA NETA SHUBHAANKAR 🙏**
